---
apiVersion: v1
kind: Secret
metadata:
  name: tanzu-rabbitmq-registry-creds
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS50YW56dS52bXdhcmUuY29tIjogewogICAgICAidXNlcm5hbWUiOiAibnNhcnZpQHZtd2FyZS5jb20iLAogICAgICAicGFzc3dvcmQiOiAiTXVydGh5MSFAdiIsCiAgICAgICJhdXRoIjogIiIKICAgIH0KICB9Cn0K

---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: dev-rmq-1
  namespace: rabbitmq-system
spec:
  replicas: 3
  imagePullSecrets:
  - name: tanzu-rabbitmq-registry-creds
